apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client # Points to client-pod.yaml -> label
  ports:
    - port: 3000
      targetPort: 3000 # container exposed port
      nodePort: 30007 # port exposed to external world
