apiVersion: v1
kind: Service
metadata:
  name: mongo-srv # This name is used by client to resolve IP using DNS service
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
