apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    name: server
spec:
  containers:
  - name: server
    image: laithharb/server:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
